### PR TITLE
Add semigroup instances to appease ghc 8.4

### PR DESCRIPTION
**Pull request by DanBurton**

### CODE REVIEW

**Comment by peti** [comment]
Ping? Can you please merge this PR and release a new version to Hackage to fix the build of this package with GHC 8.4.1?

**Comment by luqui** [comment]
Uploaded as data-inttrie-0.1.3

**Comment by peti** [comment]
That new version does not help. It has a constraint on `base ==4.10.*` and therefore still doesn't build with GHC 8.4.1, which comes with `base-4.11.0.0`.

**Comment by peti** [comment]
>  I don't have GHC 8.4.1 installed so I can't test.

Check out https://github.com/luqui/data-inttrie/pull/8 for how to remedy that situation easily. There are free services that will run those tests for you automatically.

**Pull request merged**
